#!/bin/bash

### BEGIN INIT INFO
# Provides:          aeacus-client
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Aeacus scoring system
### END INIT INFO

start() {
   start-stop-daemon -S -m -p /run/aeacus-client.pid -b -C -x "/opt/aeacus/phocus"
}

stop() {
   start-stop-daemon -K --remove-pidfile -q -p /run/aeacus-client.pid
}

case "$1" in
start)
   start $@
   ;;
stop)
   echo "Why are you trying to stop the engine? :thinking:"
   ;;
restart)
   stop
   start $@
   ;;
status)
   start-stop-daemon -T -p /run/aeacus-client.pid && engine="running" || engine="stopped"
   echo "aeacus is $engine"
   ;;
*)
   echo "Usage: $0 {start|stop|status}"
   ;;
esac

exit 0
