before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - id: aeacus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    flags:
      - -v
    goarch:
      - amd64

  - id: phocus
    binary: phocus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    flags:
      - -v
      - -tags=phocus
    goarch:
      - amd64

archives:
  - wrap_in_directory: true
    replacements:
      amd64: x86_64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - assets/**
      - misc/**

checksum:
  name_template: "checksums.txt"
  algorithm: sha512

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
